//Web push notification
    Push.create("New Sales Order", {
        body: "Sales order: has been successfully created!",
        icon: 'https://dxpdemo.neptune-software.cloud/media/root/PDF%20Generator%20App/neptune_logo.png',
        timeout: 6000,
        onClick: function () {
            window.focus();
            this.close();
        }
    });

    sap.m.MessageToast.show("Sales Order sucessfully created!");
